# What Are Tensors?


In machine learning and deep learning, tensors are the fundamental data structures used for computation. They can be thought of as generalized matrices that are used to represent data in higher dimensions. In simple terms, tensors are multi-dimensional arrays that can store data in various forms such as scalars, vectors, and matrices.

Tensors are used extensively in machine learning frameworks like TensorFlow and PyTorch for operations on large datasets, especially when working with neural networks. They allow us to represent data in multiple dimensions, making it easier to perform complex computations on the data efficiently.

# 0D Tensor/Scalars

In [2]:
import numpy as np

a = np.array(2)

In [3]:
a

array(2)

**Count No Of Dimensions**

In [4]:
np.ndim(a)

0

# 1D Tensor/Vector

In [5]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [6]:
np.ndim(arr)

1

# 2D Tensor/Matrices 

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.ndim(matrix)

2

In [2]:
import tensorflow as tf

# Creating a 1-D Tensor (Vector)
vector = tf.constant([1, 2, 3, 4, 5])

# Creating a 2-D Tensor (Matrix)
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])

# Creating a 3-D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [3]:
print(vector)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [4]:
print(matrix)


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [5]:

print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
